version: "3.4"

services:

  jupyterlab:
    image: laminr
    build:
      context: ./
      dockerfile: ./Dockerfile
      # args:
      #   - GITHUB_USER=${GITHUB_USER}
      #   - DEV_SOURCE=${DEV_SOURCE}
      #   - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/project
      # - /var/sinz-shared:/project/data
    # env_file:
    #   - .env
    entrypoint:
      - jupyter
      - lab
      - --allow-root