version: "3.4"

services:

  examples:
    image: laminr
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    working_dir: /project/examples
    entrypoint:
      - jupyter
      - lab
      - --allow-root
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser

  jupyterlab:
    image: laminr
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    working_dir: /project/notebooks
    entrypoint:
      - jupyter
      - lab
      - --allow-root
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser

  dev:
    image: laminr
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - .:/project
    working_dir: /project
    entrypoint:
      - jupyter
      - lab
      - --allow-root
      - --ip=0.0.0.0
      - --port=8888
      - --no-browser
